#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib_e
	x = y = 1
	sum = 0
	while sum < 4000000
		sum += (x + y)
		x, y = x + 2 * y, 2 * x + 3 * y
	end
	return sum
end

p fib_e



